version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8001:8000'
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn PhotoManager.wsgi -b :8000"
    volumes:
      - static_value_photo:/code/static/
      - media_value_photo:/code/media/
      - .env.docker:/code/.env
  db:
    restart: always
    image: postgres:15.0-alpine
    container_name: photo_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mail_app" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  media_value_photo:
  static_value_photo: